name: Clone, Run Script, and Create PR

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the current repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      # Step 2: Set up Git user identity
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 3: Clone the public repository and copy print.py
      - name: Clone public repository and copy script
        run: |
          git clone --depth 1 https://github.com/matejnovak29/testingrepository2.git
          cp testingrepository2/print.py .

      # Step 4: Run the Python script with the secret value
      - name: Run Python script
        env:
          TEST_VALUE: ${{ secrets.TEST_VALUE }}  # Inject secret value
        run: python print.py

      # Step 5: Commit print.py to a new branch
      - name: Commit cloned file to a new branch
        run: |
          git checkout -b new-feature-branch
          git add print.py
          git commit -m "Add print.py from testingrepository2"
          git push origin new-feature-branch

      # Step 6: Create a pull request using GH_PAT
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Use Personal Access Token (GH_PAT)
        run: |
          gh pr create \
            --title "Add print.py from testingrepository2" \
            --body "This PR adds the print.py file from testingrepository2." \
            --base main \
            --head new-feature-branch
