name: Create PR in Client's Repo with Terraform Setup

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository (Repo A)
      - name: Checkout Repo A
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"

      # Step 3: Terraform Init and Apply
      - name: Initialize and Apply Terraform
        env:
          TF_VAR_dbt_cloud_api_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          TF_VAR_dbt_cloud_account_id: "15960"
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: terraform output -raw dbt_cloud_job_id
