name: Create PR on Push to Main

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Step 3: Pull latest changes from the remote branch
      - name: Pull latest changes
        run: git pull origin main

      # Step 4: Create and commit a new Python file
      - name: Add a new Python file
        run: |
          git checkout -b new-feature-branch
          echo 'print("Hello World!")' > hello_world.py
          git add hello_world.py
          git commit -m "Add hello_world.py"
          git push origin new-feature-branch

      # Step 5: Create a pull request
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --title "Auto-created Pull Request" \
            --body "This PR was automatically created after a push to main and adds hello_world.py." \
            --base main \
            --head new-feature-branch
