name: Create PR on Push to Main

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up the GitHub CLI (gh)
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Step 3: Authenticate with GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "${GITHUB_TOKEN}"

      # Step 4: Create a new branch
      - name: Create a new branch
        run: |
          git checkout -b new-feature-branch
          git push origin new-feature-branch

      # Step 5: Create a pull request
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Auto-created Pull Request" \
            --body "This PR was automatically created after a push to main." \
            --base main \
            --head new-feature-branch
