name: Clone and Run Python Script with Secret

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      # Step 2: Clone the public repository and copy print.py
      - name: Clone public repository
        run: |
          git clone --depth 1 https://github.com/matejnovak29/testingrepository2.git
          cp testingrepository2/print.py .

      # Step 3: Run the Python script with the secret
      - name: Run Python script
        env:
          TEST_VALUE: ${{ secrets.TEST_VALUE }}  # Pass the secret as an environment variable
        run: python print.py
