name: Create PR to another repo

on:
  workflow_dispatch:  # Spustit CI/CD manuálně

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository (Repo A)
      - name: Checkout Repo A
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 3: Clone Client Repo (Repo B)
      - name: Clone Client Repo (Repo B)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${GH_PAT}@github.com/matejnovak29/testingrepository.git client-repo

      # Step 4: Copy Airflow DAG Template to Repo B
      - name: Copy Template
        run: |
          if [ ! -d "client-repo/airflow_dbt_cloud_dags" ]; then
            mkdir -p client-repo/airflow_dbt_cloud_dags
          fi
          cp templates/airflow_dag.py client-repo/airflow_dbt_cloud_dags/
          cd client-repo
          git checkout -b feature/airflow-dag-template
          git add airflow_dags/airflow_dag.py
          git commit -m "Add Airflow DAG Template"
          git push origin feature/airflow-dag-template

      # Step 5: Create Pull Request
      - name: Create Pull Request
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --title "Add Airflow DAG Template" \
            --body "This PR adds the Airflow DAG Template from Repo A." \
            --base main \
            --head feature/airflow-dag-template
