name: Create PR in Client's Repo

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository (Repo A)
      - name: Checkout Repo A
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 3: Clone Client Repo (Repo B)
      - name: Clone Client Repo (Repo B)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${GH_PAT}@github.com/matejnovak29/testingrepository2.git client-repo

      # Step 4: Copy Airflow DAG Template to Client Repo
      - name: Copy Template to Client Repo
        run: |
          # Ensure the target directory exists
          if [ ! -d "client-repo/airflow_dbt_cloud_dags" ]; then
            mkdir -p client-repo/airflow_dbt_cloud_dags
          fi

          # Copy the template to the target directory
          cp templates/airflow_dag.py client-repo/airflow_dbt_cloud_dags/

      # Step 5: Commit and Push Changes to a New Branch in Client Repo
      - name: Commit and Push Changes to Client Repo
        run: |
          cd client-repo

          # Create and switch to a new branch
          git checkout -b feature/airflow-dag-template

          # Add the copied file
          git add airflow_dbt_cloud_dags/airflow_dag.py

          # Commit changes
          git commit -m "Add Airflow DAG Template"

          # Push the new branch to the client repository
          git push origin feature/airflow-dag-template

      # Step 6: Create Pull Request in Client Repo
      - name: Create Pull Request in Client Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --repo matejnovak29/testingrepository2 \
            --title "Add Airflow DAG Template" \
            --body "This PR adds the Airflow DAG Template from Repo A." \
            --base main \
            --head feature/airflow-dag-template
